// Code generated by entc, DO NOT EDIT.

package nas

import (
	"mify_api_radius/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Nasname applies equality check predicate on the "nasname" field. It's identical to NasnameEQ.
func Nasname(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNasname), v))
	})
}

// NasnameEQ applies the EQ predicate on the "nasname" field.
func NasnameEQ(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNasname), v))
	})
}

// NasnameNEQ applies the NEQ predicate on the "nasname" field.
func NasnameNEQ(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNasname), v))
	})
}

// NasnameIn applies the In predicate on the "nasname" field.
func NasnameIn(vs ...string) predicate.Nas {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Nas(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNasname), v...))
	})
}

// NasnameNotIn applies the NotIn predicate on the "nasname" field.
func NasnameNotIn(vs ...string) predicate.Nas {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Nas(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNasname), v...))
	})
}

// NasnameGT applies the GT predicate on the "nasname" field.
func NasnameGT(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNasname), v))
	})
}

// NasnameGTE applies the GTE predicate on the "nasname" field.
func NasnameGTE(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNasname), v))
	})
}

// NasnameLT applies the LT predicate on the "nasname" field.
func NasnameLT(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNasname), v))
	})
}

// NasnameLTE applies the LTE predicate on the "nasname" field.
func NasnameLTE(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNasname), v))
	})
}

// NasnameContains applies the Contains predicate on the "nasname" field.
func NasnameContains(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNasname), v))
	})
}

// NasnameHasPrefix applies the HasPrefix predicate on the "nasname" field.
func NasnameHasPrefix(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNasname), v))
	})
}

// NasnameHasSuffix applies the HasSuffix predicate on the "nasname" field.
func NasnameHasSuffix(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNasname), v))
	})
}

// NasnameEqualFold applies the EqualFold predicate on the "nasname" field.
func NasnameEqualFold(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNasname), v))
	})
}

// NasnameContainsFold applies the ContainsFold predicate on the "nasname" field.
func NasnameContainsFold(v string) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNasname), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Nas) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Nas) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Nas) predicate.Nas {
	return predicate.Nas(func(s *sql.Selector) {
		p(s.Not())
	})
}
