// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"mify_api_radius/ent/migrate"

	"mify_api_radius/ent/nas"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Nas is the client for interacting with the Nas builders.
	Nas *NasClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Nas = NewNasClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Nas:    NewNasClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Nas:    NewNasClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Nas.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Nas.Use(hooks...)
}

// NasClient is a client for the Nas schema.
type NasClient struct {
	config
}

// NewNasClient returns a client for the Nas from the given config.
func NewNasClient(c config) *NasClient {
	return &NasClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `nas.Hooks(f(g(h())))`.
func (c *NasClient) Use(hooks ...Hook) {
	c.hooks.Nas = append(c.hooks.Nas, hooks...)
}

// Create returns a create builder for Nas.
func (c *NasClient) Create() *NasCreate {
	mutation := newNasMutation(c.config, OpCreate)
	return &NasCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Nas entities.
func (c *NasClient) CreateBulk(builders ...*NasCreate) *NasCreateBulk {
	return &NasCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Nas.
func (c *NasClient) Update() *NasUpdate {
	mutation := newNasMutation(c.config, OpUpdate)
	return &NasUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NasClient) UpdateOne(n *Nas) *NasUpdateOne {
	mutation := newNasMutation(c.config, OpUpdateOne, withNas(n))
	return &NasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NasClient) UpdateOneID(id int) *NasUpdateOne {
	mutation := newNasMutation(c.config, OpUpdateOne, withNasID(id))
	return &NasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Nas.
func (c *NasClient) Delete() *NasDelete {
	mutation := newNasMutation(c.config, OpDelete)
	return &NasDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *NasClient) DeleteOne(n *Nas) *NasDeleteOne {
	return c.DeleteOneID(n.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *NasClient) DeleteOneID(id int) *NasDeleteOne {
	builder := c.Delete().Where(nas.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NasDeleteOne{builder}
}

// Query returns a query builder for Nas.
func (c *NasClient) Query() *NasQuery {
	return &NasQuery{
		config: c.config,
	}
}

// Get returns a Nas entity by its id.
func (c *NasClient) Get(ctx context.Context, id int) (*Nas, error) {
	return c.Query().Where(nas.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NasClient) GetX(ctx context.Context, id int) *Nas {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NasClient) Hooks() []Hook {
	return c.hooks.Nas
}
