// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mify_api_radius/ent/nas"
	"mify_api_radius/ent/predicate"
	"sync"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeNas = "Nas"
)

// NasMutation represents an operation that mutates the Nas nodes in the graph.
type NasMutation struct {
	config
	op            Op
	typ           string
	id            *int
	nasname       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Nas, error)
	predicates    []predicate.Nas
}

var _ ent.Mutation = (*NasMutation)(nil)

// nasOption allows management of the mutation configuration using functional options.
type nasOption func(*NasMutation)

// newNasMutation creates new mutation for the Nas entity.
func newNasMutation(c config, op Op, opts ...nasOption) *NasMutation {
	m := &NasMutation{
		config:        c,
		op:            op,
		typ:           TypeNas,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNasID sets the ID field of the mutation.
func withNasID(id int) nasOption {
	return func(m *NasMutation) {
		var (
			err   error
			once  sync.Once
			value *Nas
		)
		m.oldValue = func(ctx context.Context) (*Nas, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Nas.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNas sets the old Nas of the mutation.
func withNas(node *Nas) nasOption {
	return func(m *NasMutation) {
		m.oldValue = func(context.Context) (*Nas, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NasMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NasMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Nas entities.
func (m *NasMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NasMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NasMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Nas.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNasname sets the "nasname" field.
func (m *NasMutation) SetNasname(s string) {
	m.nasname = &s
}

// Nasname returns the value of the "nasname" field in the mutation.
func (m *NasMutation) Nasname() (r string, exists bool) {
	v := m.nasname
	if v == nil {
		return
	}
	return *v, true
}

// OldNasname returns the old "nasname" field's value of the Nas entity.
// If the Nas object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NasMutation) OldNasname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNasname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNasname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNasname: %w", err)
	}
	return oldValue.Nasname, nil
}

// ResetNasname resets all changes to the "nasname" field.
func (m *NasMutation) ResetNasname() {
	m.nasname = nil
}

// Where appends a list predicates to the NasMutation builder.
func (m *NasMutation) Where(ps ...predicate.Nas) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *NasMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Nas).
func (m *NasMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NasMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.nasname != nil {
		fields = append(fields, nas.FieldNasname)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NasMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case nas.FieldNasname:
		return m.Nasname()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NasMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case nas.FieldNasname:
		return m.OldNasname(ctx)
	}
	return nil, fmt.Errorf("unknown Nas field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NasMutation) SetField(name string, value ent.Value) error {
	switch name {
	case nas.FieldNasname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNasname(v)
		return nil
	}
	return fmt.Errorf("unknown Nas field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NasMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NasMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NasMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Nas numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NasMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NasMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NasMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Nas nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NasMutation) ResetField(name string) error {
	switch name {
	case nas.FieldNasname:
		m.ResetNasname()
		return nil
	}
	return fmt.Errorf("unknown Nas field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NasMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NasMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NasMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NasMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NasMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NasMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NasMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Nas unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NasMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Nas edge %s", name)
}
