// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"mify_api_radius/ent/nas"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Nas is the model entity for the Nas schema.
type Nas struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Nasname holds the value of the "nasname" field.
	Nasname string `json:"nasname,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Nas) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case nas.FieldID:
			values[i] = new(sql.NullInt64)
		case nas.FieldNasname:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Nas", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Nas fields.
func (n *Nas) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nas.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		case nas.FieldNasname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nasname", values[i])
			} else if value.Valid {
				n.Nasname = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Nas.
// Note that you need to call Nas.Unwrap() before calling this method if this Nas
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Nas) Update() *NasUpdateOne {
	return (&NasClient{config: n.config}).UpdateOne(n)
}

// Unwrap unwraps the Nas entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Nas) Unwrap() *Nas {
	tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Nas is not a transactional entity")
	}
	n.config.driver = tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Nas) String() string {
	var builder strings.Builder
	builder.WriteString("Nas(")
	builder.WriteString(fmt.Sprintf("id=%v", n.ID))
	builder.WriteString(", nasname=")
	builder.WriteString(n.Nasname)
	builder.WriteByte(')')
	return builder.String()
}

// NasSlice is a parsable slice of Nas.
type NasSlice []*Nas

func (n NasSlice) config(cfg config) {
	for _i := range n {
		n[_i].config = cfg
	}
}
